<?php

use Illuminate\Database\Seeder;

class MsTenantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ms_tenant')->insert([
        [
            'tenan_code' => 'TN160101001',
            'tenan_name' => 'MONALISA',
            'tenan_idno' => '3275120605840001',
            'tenan_phone' => '081284381443',
            'tenan_fax' => NULL,
            'tenan_email' => 'monalisa99@gmail.com',
            'tenan_address' => 'Apartemen Cityloft Lt.1 Unit 01P Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_npwp' => '092542943407000',
            'tenan_taxname' => 'MONALISA',
            'tenan_tax_address' => 'Apartemen Cityloft Lt.1 Unit 01P Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => FALSE,
            'tent_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101002',
            'tenan_name' => 'ALEXINDO, PT',
            'tenan_idno' => '3372032503850004',
            'tenan_phone' => '021982657123',
            'tenan_fax' => '021982657123',
            'tenan_email' => 'wayan.kurniawan@alexindo.com',
            'tenan_address' => 'Apartemen Cityloft Lt.1 Unit 01S Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_npwp' => '313640054603000',
            'tenan_taxname' => 'PT ALEXINDO',
            'tenan_tax_address' => 'Apartemen Cityloft Lt.1 Unit 01S Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => TRUE,
            'tent_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101003',
            'tenan_name' => 'SADAR SUBAGYO',
            'tenan_idno' => '1221064502790001',
            'tenan_phone' => '081345678923',
            'tenan_fax' => NULL,
            'tenan_email' => 'sadar22@gmail.com',
            'tenan_address' => 'Apartemen Cityloft Lt.1 Unit 02P Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_npwp' => '323650054604000',
            'tenan_taxname' => 'SADAR SUBAGYO',
            'tenan_tax_address' => 'Apartemen Cityloft Lt.1 Unit 02P Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => FALSE,
            'tent_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101004',
            'tenan_name' => 'HENDRAWAN',
            'tenan_idno' => '4372035503840004',
            'tenan_phone' => '081347823456',
            'tenan_fax' => NULL,
            'tenan_email' => 'hi.world@gmail.com',
            'tenan_address' => 'Apartemen Cityloft Lt.1 Unit 03M Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_npwp' => '315670054605110',
            'tenan_taxname' => 'HENDRAWAN',
            'tenan_tax_address' => 'Apartemen Cityloft Lt.1 Unit 03M Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => FALSE,
            'tent_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101005',
            'tenan_name' => 'NERVE MITRA TEKNOLOGI, PT',
            'tenan_idno' => '3272092503880006',
            'tenan_phone' => '081284291556',
            'tenan_fax' => '021987234567',
            'tenan_email' => 'rachmat@nervetekno.com',
            'tenan_address' => 'Apartemen Cityloft Lt.1 Unit 04K Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_npwp' => '313640054603000',
            'tenan_taxname' => 'PT NERVE MITRA TEKNOLOGI',
            'tenan_tax_address' => 'Apartemen Cityloft Lt.1 Unit 04K Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => TRUE,
            'tent_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101006',
            'tenan_name' => 'WAHYU SETIAWAN',
            'tenan_idno' => '5374032503850334',
            'tenan_phone' => '0812345678123',
            'tenan_fax' => '021982657123',
            'tenan_email' => 'wahyu.s@gmail.com',
            'tenan_address' => 'Apartemen Cityloft Lt.1 Unit 05Z Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_npwp' => '613645054703800',
            'tenan_taxname' => 'WAHYU SETIAWAN',
            'tenan_tax_address' => 'Apartemen Cityloft Lt.1 Unit 05Z Jl.KH. Mas Mansyur No. 121, Jak-Pus',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => FALSE,
            'tent_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101007',
            'tenan_name' => 'SETIADI WIJAYA',
            'tenan_idno' => '3568032503850001',
            'tenan_phone' => '08123456789',
            'tenan_fax' => NULL,
            'tenan_email' => 's.wijaya@gmail.com',
            'tenan_address' => 'Gandaria 8 Jakarta Unit K-502, Jak-Sel',
            'tenan_npwp' => '556640054603005',
            'tenan_taxname' => 'SETIADI WIJAYA',
            'tenan_tax_address' => 'Gandaria 8 Jakarta Unit K-502, Jak-Sel',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => FALSE,
            'tent_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101008',
            'tenan_name' => 'PROPERTY JAYA, PT',
            'tenan_idno' => '9568032503850003',
            'tenan_phone' => '0219872345678',
            'tenan_fax' => '0219872345678',
            'tenan_email' => 'finance@jayaproperty.com',
            'tenan_address' => 'Pakubuwono Raya Jakarta Unit K-506, Jak-Sel',
            'tenan_npwp' => '996640054603006',
            'tenan_taxname' => 'PT PROPERTY JAYA',
            'tenan_tax_address' => 'Pakubuwono Raya Jakarta Unit K-506, Jak-Sel',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => TRUE,
            'tent_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ],
        [
            'tenan_code' => 'TN160101009',
            'tenan_name' => 'EXCELCO, PT',
            'tenan_idno' => '1068032503850005',
            'tenan_phone' => '02134578723',
            'tenan_fax' => '02134578723',
            'tenan_email' => 'finance@excelco.com',
            'tenan_address' => 'Fatmawati Raya Jakarta, Jak-Sel',
            'tenan_npwp' => '997740056603006',
            'tenan_taxname' => 'PT EXCELCO',
            'tenan_tax_address' => 'Fatmawati Raya Jakarta, Jak-Sel',
            'tenan_isppn' => TRUE,
            'tenan_ispkp' => TRUE,
            'tent_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'deleted_at' => NULL,
        ]
        ]);
    }
}
