<?php

use Illuminate\Database\Seeder;

class TrInvoicePaymhdrSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tr_invoice_paymhdr')->insert([
        [
            'invpayh_date' => '2016-02-02',
            'invpayh_checkno' => 'BA 000113',
            'invpayh_giro' => '2016-02-02',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-03',
            'invpayh_checkno' => 'BA 000114',
            'invpayh_giro' => '2016-02-04',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-03',
            'invpayh_checkno' => 'BA 000115',
            'invpayh_giro' => '2016-02-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 3,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-03',
            'invpayh_checkno' => 'BA 000116',
            'invpayh_giro' => '2016-02-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 4,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-03',
            'invpayh_checkno' => 'BA 000117',
            'invpayh_giro' => '2016-02-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 5,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-03',
            'invpayh_checkno' => 'BA 000120',
            'invpayh_giro' => '2016-02-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 6,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-10',
            'invpayh_checkno' => 'BA 000121',
            'invpayh_giro' => '2016-02-10',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 7,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-11',
            'invpayh_checkno' => 'BA 000122',
            'invpayh_giro' => '2016-02-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '961650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 8,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-12',
            'invpayh_checkno' => 'BA 000123',
            'invpayh_giro' => '2016-02-12',
            'invpayh_note' => NULL,
            'invpayh_amount' => '499650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 9,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-13',
            'invpayh_checkno' => 'BA 000124',
            'invpayh_giro' => '2016-02-13',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 10,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-11',
            'invpayh_checkno' => 'BA 000125',
            'invpayh_giro' => '2016-02-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 11,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-02-11',
            'invpayh_checkno' => 'BA 000122',
            'invpayh_giro' => '2016-02-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '961650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 12,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-02',
            'invpayh_checkno' => 'BA 000113',
            'invpayh_giro' => '2016-03-02',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-03',
            'invpayh_checkno' => 'BA 000114',
            'invpayh_giro' => '2016-03-04',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-03',
            'invpayh_checkno' => 'BA 000115',
            'invpayh_giro' => '2016-03-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 3,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-03',
            'invpayh_checkno' => 'BA 000116',
            'invpayh_giro' => '2016-03-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 4,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-03',
            'invpayh_checkno' => 'BA 000117',
            'invpayh_giro' => '2016-03-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 5,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-03',
            'invpayh_checkno' => 'BA 000120',
            'invpayh_giro' => '2016-03-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 6,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-10',
            'invpayh_checkno' => 'BA 000121',
            'invpayh_giro' => '2016-03-10',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 7,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-11',
            'invpayh_checkno' => 'BA 000122',
            'invpayh_giro' => '2016-03-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '961650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 8,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-12',
            'invpayh_checkno' => 'BA 000123',
            'invpayh_giro' => '2016-03-12',
            'invpayh_note' => NULL,
            'invpayh_amount' => '499650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 9,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-13',
            'invpayh_checkno' => 'BA 000124',
            'invpayh_giro' => '2016-03-13',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 10,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-11',
            'invpayh_checkno' => 'BA 000125',
            'invpayh_giro' => '2016-03-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 11,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-03-11',
            'invpayh_checkno' => 'BA 000122',
            'invpayh_giro' => '2016-03-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '961650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 12,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-02',
            'invpayh_checkno' => 'BA 000113',
            'invpayh_giro' => '2016-04-02',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-03',
            'invpayh_checkno' => 'BA 000114',
            'invpayh_giro' => '2016-04-04',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-03',
            'invpayh_checkno' => 'BA 000115',
            'invpayh_giro' => '2016-04-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 3,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-03',
            'invpayh_checkno' => 'BA 000116',
            'invpayh_giro' => '2016-04-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 4,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-03',
            'invpayh_checkno' => 'BA 000117',
            'invpayh_giro' => '2016-04-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 5,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-03',
            'invpayh_checkno' => 'BA 000120',
            'invpayh_giro' => '2016-04-05',
            'invpayh_note' => NULL,
            'invpayh_amount' => '1061750',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 6,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-10',
            'invpayh_checkno' => 'BA 000121',
            'invpayh_giro' => '2016-04-10',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 7,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-11',
            'invpayh_checkno' => 'BA 000122',
            'invpayh_giro' => '2016-04-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '961650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 8,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-12',
            'invpayh_checkno' => 'BA 000123',
            'invpayh_giro' => '2016-04-12',
            'invpayh_note' => NULL,
            'invpayh_amount' => '499650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 9,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-13',
            'invpayh_checkno' => 'BA 000124',
            'invpayh_giro' => '2016-04-13',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 10,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-11',
            'invpayh_checkno' => 'BA 000125',
            'invpayh_giro' => '2016-04-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '725150',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 11,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ],
        [
            'invpayh_date' => '2016-04-11',
            'invpayh_checkno' => 'BA 000122',
            'invpayh_giro' => '2016-04-11',
            'invpayh_note' => NULL,
            'invpayh_amount' => '961650',
            'invpayh_settlamt' => 0,
            'invpayh_adjustamt' => 0,
            'invpayh_post' => FALSE,
            'posting_at' => NULL,
            'paymtp_code' => 2,
            'posting_by' => NULL,
            'cashbk_id' => 1,
            'contr_id' => 12,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s")
        ]
        ]);
    }
}
