<?php

use Illuminate\Database\Seeder;

class TrInvoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tr_invoice')->insert([
        [
            'tenan_id' => '7',
            'inv_number' => 'MN-1602-0001',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1602-0001',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '7',
            'inv_number' => 'MN-1602-0002',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1602-0002',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '8',
            'inv_number' => 'MN-1602-0003',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1602-0003',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 3,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '8',
            'inv_number' => 'MN-1602-0004',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1602-0004',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 4,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '9',
            'inv_number' => 'MN-1602-0005',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1602-0005',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 5,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '9',
            'inv_number' => 'MN-1602-0006',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1602-0006',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 6,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '1',
            'inv_number' => 'UT-1602-0007',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1602-0006',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 7,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '2',
            'inv_number' => 'UT-1602-0008',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '961650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '87150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1602-0008',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 8,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '3',
            'inv_number' => 'UT-1602-0009',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '499650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '45150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1602-0009',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 9,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '4',
            'inv_number' => 'UT-1602-0010',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1602-0010',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 10,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '5',
            'inv_number' => 'UT-1602-0011',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1602-0011',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 11,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '6',
            'inv_number' => 'UT-1602-0012',
            'inv_date' => '2016-02-01',
            'inv_duedate' => '2016-02-29',
            'inv_amount' => '961650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '87150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1602-0012',
            'inv_faktur_date' => '2016-02-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 12,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '7',
            'inv_number' => 'MN-1603-0001',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1603-0001',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '7',
            'inv_number' => 'MN-1603-0002',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1603-0002',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '8',
            'inv_number' => 'MN-1603-0003',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1603-0003',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 3,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '8',
            'inv_number' => 'MN-1603-0004',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1603-0004',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 4,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '9',
            'inv_number' => 'MN-1603-0005',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1603-0005',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 5,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '9',
            'inv_number' => 'MN-1603-0006',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1603-0006',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 6,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '1',
            'inv_number' => 'UT-1603-0007',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1603-0006',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 7,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '2',
            'inv_number' => 'UT-1603-0008',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '961650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '87150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1603-0008',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 8,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '3',
            'inv_number' => 'UT-1603-0009',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '499650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '45150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1603-0009',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 9,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '4',
            'inv_number' => 'UT-1603-0010',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1603-0010',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 10,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '5',
            'inv_number' => 'UT-1603-0011',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1603-0011',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 11,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '6',
            'inv_number' => 'UT-1603-0012',
            'inv_date' => '2016-03-01',
            'inv_duedate' => '2016-03-31',
            'inv_amount' => '961650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '87150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1603-0012',
            'inv_faktur_date' => '2016-03-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 12,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '7',
            'inv_number' => 'MN-1604-0001',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1604-0001',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 1,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '7',
            'inv_number' => 'MN-1604-0002',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1604-0002',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 2,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '8',
            'inv_number' => 'MN-1604-0003',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1604-0003',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 3,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '8',
            'inv_number' => 'MN-1604-0004',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1604-0004',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 4,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '9',
            'inv_number' => 'MN-1604-0005',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1604-0005',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 5,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '9',
            'inv_number' => 'MN-1604-0006',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '1061750',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '96250',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'MN-1604-0006',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 2,
            'contr_id' => 6,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '1',
            'inv_number' => 'UT-1604-0007',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1604-0006',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 7,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '2',
            'inv_number' => 'UT-1604-0008',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '961650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '87150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1604-0008',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 8,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '3',
            'inv_number' => 'UT-1604-0009',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '499650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '45150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1604-0009',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 9,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '4',
            'inv_number' => 'UT-1604-0010',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1604-0010',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 10,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '5',
            'inv_number' => 'UT-1604-0011',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '725150',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '65650',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1604-0011',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 11,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'tenan_id' => '6',
            'inv_number' => 'UT-1604-0012',
            'inv_date' => '2016-04-01',
            'inv_duedate' => '2016-04-30',
            'inv_amount' => '961650',
            'inv_ppn' => '0.1',
            'inv_ppn_amount' => '87150',
            'inv_outstanding' => '0',
            'inv_faktur_no' => 'UT-1604-0012',
            'inv_faktur_date' => '2016-04-01',
            'inv_iscancel' => FALSE,
            'inv_post' => FALSE,
            'invtp_code' => 1,
            'contr_id' => 12,
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ]
        ]);
    }
}
