-- roles --
INSERT INTO "roles" ("id", "name", "created_at", "updated_at") VALUES (1, 'Superadmin', NULL, NULL);
INSERT INTO "roles" ("id", "name", "created_at", "updated_at") VALUES (2, 'Tenant Relation', NULL, NULL);
INSERT INTO "roles" ("id", "name", "created_at", "updated_at") VALUES (3, 'Supervisor', NULL, NULL);
INSERT INTO "roles" ("id", "name", "created_at", "updated_at") VALUES (4, 'Finance', NULL, NULL);
-- user has roles --
INSERT INTO "user_has_roles" ("role_id", "user_id") VALUES (1, 1);
-- permission --
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (1, 'View Department', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (2, 'Add Department', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (3, 'Edit Department', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (4, 'Delete Department', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (5, 'Edit Company Details', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (6, 'Edit Config', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (7, 'View Invoice Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (8, 'Add Invoice Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (9, 'Edit Invoice Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (10, 'Delete Invoice Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (11, 'View COA', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (12, 'Add COA', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (13, 'Edit COA', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (14, 'Delete COA', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (15, 'View Unit', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (16, 'Add Unit', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (17, 'Edit Unit', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (18, 'Delete Unit', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (19, 'View Unit Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (20, 'Add Unit Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (21, 'Edit Unit Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (22, 'Delete Unit Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (23, 'View Floor', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (24, 'Add Floor', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (25, 'Edit Floor', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (26, 'Delete Floor', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (27, 'View Tenant', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (28, 'Add Tenant', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (29, 'Edit Tenant', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (30, 'Delete Tenant', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (31, 'View Tenant Type ', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (32, 'Add Tenant Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (33, 'Edit Tenant Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (34, 'Delete Tenant Type', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (35, 'View Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (36, 'Add Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (37, 'Edit Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (38, 'Delete Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (39, 'Confirm Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (40, 'Addendum Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (41, 'Renew Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (42, 'Terminate Billing Information', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (43, 'Close Billing Information at Reminder', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (44, 'View Component Billing', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (45, 'Add Component Billing', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (46, 'Edit Component Billing', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (47, 'Delete Component Billing', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (48, 'Add Component Billing Detail', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (49, 'Edit Component Billing Detail', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (50, 'Delete Component Billing Detail', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (51, 'View Tenancy Reports', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (52, 'View Meter Input', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (53, 'Add Meter Input', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (54, 'Edit Meter Input', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (55, 'Delete Meter Input', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (56, 'Approve Meter Input', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (57, 'Unpost Meter Input', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (58, 'Generate Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (59, 'View Invoices', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (60, 'Add Invoice Lain', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (61, 'Posting Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (62, 'Cancel Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (63, 'View Aging Invoices', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (64, 'View Journal', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (65, 'Add Journal', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (66, 'Edit Journal', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (67, 'Delete Journal', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (68, 'View Payment Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (69, 'Add Payment Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (70, 'Posting Payment Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (71, 'Void Payment Invoice', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (72, 'View Cash Bank', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (73, 'Add Cash Bank', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (74, 'Edit Cash Bank', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (75, 'Delete Cash Bank', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (76, 'View Finance Reports', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (77, 'View Reminder', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (78, 'Edit Reminder', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (79, 'Send Reminder', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (80, 'View Fixed Asset', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (81, 'Add Fixed Asset', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (82, 'Edit Fixed Asset', NULL, NULL);
INSERT INTO "permissions" ("id", "name", "created_at", "updated_at") VALUES (83, 'Delete Fixed Asset', NULL, NULL);
